export enum BurgerAction {
    GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST',
    GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS',
    GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR',
    CONSTRUCTOR_ADD_BUN = 'CONSTRUCTOR_ADD_BUN',
    CONSTRUCTOR_ADD = 'CONSTRUCTOR_ADD',
    CONSTRUCTOR_DELETE = 'CONSTRUCTOR_DELETE',
    ORDER_REQUEST = 'ORDER_REQUEST',
    ORDER_SUCCESS = 'ORDER_SUCCESS',
    ORDER_ERROR = 'ORDER_ERROR',
    ORDER_CLEAR = 'ORDER_CLEAR',
    SELECT_INGREDIENT = 'SELECT_INGREDIENT',
    DND_REORDER_INGREDIENTS = 'DND_REORDER_INGREDIENTS',
}