export enum FeedAction {
    FEED_WS_CONNECTION_SUCCESS = 'FEED_WS_CONNECTION_SUCCESS',
    FEED_WS_CONNECTION_ERROR = 'FEED_WS_CONNECTION_ERROR',
    FEED_WS_GET_MESSAGE = 'FEED_WS_GET_MESSAGE',
    FEED_WS_CONNECTION_CLOSED = 'FEED_WS_CONNECTION_CLOSED',
    FEED_WS_CONNECTION_START = 'FEED_WS_CONNECTION_START',
    FEED_SELECT_ORDER = 'FEED_SELECT_ORDER',

    FEED_GET_ORDER_FROM_SERVER = 'FEED_GET_ORDER_FROM_SERVER',
    FEED_ERROR_ORDER_FROM_SERVER = 'FEED_ERROR_ORDER_FROM_SERVER',
}